export enum Type {
  ALL = 'ALL', COSQUILLEO = 'COSQUILLEO', FLETEO = 'FLETEO', INTERNET = 'INTERNET', VEHICULO = 'VEHICULO', RESIDENCIAL = 'RESIDENCIAL', VIOLACION = 'VIOLACION', ASESINATO = 'ASESINATO', OTRO = 'OTRO'
}
